site_name: MCDI JIRA Manual
pages:
  - User Guide:
    - Home: index.md
    - Setup: setup.md
    - Site Layout: layout.md
    - Working With Issues: working_with_issues.md
    - Default Workflow Usage: workflows.md
    - Document Management: document_management.md
    - Calendar Functionality: calendar.md
    - Filters: filters.md
    - Reports: reports.md
  - JIRA Core Notes:
    - Core Issue Types: core_issue_types.md
  - JIRA Software Notes:
    - Software Issue Types: software_issue_types.md
  - Release Notes:
    - 0.1.1.3 (11/03/2016): 0113_11032016.md
    - 0.1.1.2 (11/02/2016): 0112_11022016.md
    - 0.1.1.1 (10/31/2016): 0111_10312016.md
    - 0.1.1.0 (10/31/2016): 0110_10312016.md

theme: readthedocs
