site_name: MCDI JIRA Manual
pages:
  - User Guide:
    - Home: index.md
    - Setup: setup.md
    - Site Layout: layout.md
    - Working With Issues: working_with_issues.md
    - Filters: filters.md
    - Reports: reports.md
    - Calendar: calendar.md
  - JIRA Conventions:
    - Comments: comments.md
    - Default Workflow Usage: workflows.md
  - Administrative Functions:
    - Start Here: adm_index.md
    - Boards: boards.md
  - JIRA Core Notes:
    - Core Issue Types: core_issue_types.md
  - JIRA Software Notes:
    - Software Issue Types: software_issue_types.md
  - Process Documents:
    - Classified Incident Reporting: process_cir.md
  - Core Plugin Documentation:
    - Documents: plugin_documents.md
    - HipChat for JIRA: plugin_hipchat.md
    - Mail.Ru Calendar: plugin_mail_ru.md
    - Smart Attachments: plugin_smart_attachments.md
  - Beta Plugin Documentation:
    - BigPicture: plugin_bigpicture.md
    - Structure: plugin_structure.md
  - Release Notes:
    - 0.1.5.0 (12/16/2016): 0150_12162016.md
    - 0.1.4.0 (12/06/2016): 0140_12062016.md
    - 0.1.3.1 (12/01/2016): 0131_12012016.md
    - 0.1.3.0 (12/01/2016): 0130_12012016.md
    - 0.1.2.1 (11/16/2016): 0121_11162016.md
    - 0.1.2.0 (11/16/2016): 0120_11162016.md
    - 0.1.1.3 (11/03/2016): 0113_11032016.md
    - 0.1.1.2 (11/02/2016): 0112_11022016.md
    - 0.1.1.1 (10/31/2016): 0111_10312016.md
    - 0.1.1.0 (10/31/2016): 0110_10312016.md

theme: readthedocs
